// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBank.Models;

#nullable disable

namespace WebBank.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20250515215327_seckin")]
    partial class seckin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBank.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("WebBank.Models.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Bakiye")
                        .HasColumnType("float");

                    b.Property<int>("HesapTuru")
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SubeId");

                    b.ToTable("HesapBilgileri");
                });

            modelBuilder.Entity("WebBank.Models.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GiseMemuruId")
                        .HasColumnType("int");

                    b.Property<int>("HesapId")
                        .HasColumnType("int");

                    b.Property<bool>("InternetUzerindenMi")
                        .HasColumnType("bit");

                    b.Property<double>("Miktar")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tur")
                        .HasColumnType("int");

                    b.Property<double>("Ucret")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GiseMemuruId");

                    b.HasIndex("HesapId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("WebBank.Models.IslemUcreti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Tur")
                        .HasColumnType("int");

                    b.Property<double>("UcretGise")
                        .HasColumnType("float");

                    b.Property<double>("UcretInternet")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IslemUcretleri");
                });

            modelBuilder.Entity("WebBank.Models.Kisiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InternetBank")
                        .HasColumnType("bit");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subeBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("WebBank.Models.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ParaMiktari")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Sube");
                });

            modelBuilder.Entity("WebBank.Models.Calisan", b =>
                {
                    b.HasOne("WebBank.Models.Sube", "Sube")
                        .WithMany("Calisanlar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("WebBank.Models.Hesap", b =>
                {
                    b.HasOne("WebBank.Models.Kisiler", "Musteri")
                        .WithMany("Hesaplar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBank.Models.Sube", "Sube")
                        .WithMany("Hesaplar")
                        .HasForeignKey("SubeId");

                    b.Navigation("Musteri");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("WebBank.Models.Islem", b =>
                {
                    b.HasOne("WebBank.Models.Calisan", "GiseMemuru")
                        .WithMany("YaptigiIslemler")
                        .HasForeignKey("GiseMemuruId");

                    b.HasOne("WebBank.Models.Hesap", "Hesap")
                        .WithMany("Islemler")
                        .HasForeignKey("HesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiseMemuru");

                    b.Navigation("Hesap");
                });

            modelBuilder.Entity("WebBank.Models.Calisan", b =>
                {
                    b.Navigation("YaptigiIslemler");
                });

            modelBuilder.Entity("WebBank.Models.Hesap", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("WebBank.Models.Kisiler", b =>
                {
                    b.Navigation("Hesaplar");
                });

            modelBuilder.Entity("WebBank.Models.Sube", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Hesaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
